### ISSUE TITLE
Switch bot's answers from Markdown to Markdown V2

### ISSUE THREAD

**Issue by rob93c** [rob93c/Stickerify#13]
Bot's answers should be moved to Markdown V2 since the standard one is the legacy mode.
The parse mode of the messages should also be updated accordingly.

Relevant classes:
* [`Answer`](https://github.com/rob93c/Stickerify/blob/main/src/main/java/com/cellar/stickerify/telegram/Answer.java)
* [`DocumentMessageBuilder`](https://github.com/rob93c/Stickerify/blob/main/src/main/java/com/cellar/stickerify/telegram/builder/DocumentMessageBuilder.java#L27)
* [`TextMessageBuilder`](https://github.com/rob93c/Stickerify/blob/main/src/main/java/com/cellar/stickerify/telegram/builder/TextMessageBuilder.java#L24)

**Comment by srikanthankamtw** [comment]
I would like to work on this issue.

**Comment by rob93c** [comment]
Hi @srikanthankamtw! Feel free to work on the ticket and let me know if you need any help 💯

**Comment by srikanthankamtw** [comment]
Yeah got it and done with it
