### ISSUE TITLE
Explain how to launch the bot using Docker

### ISSUE THREAD

**Issue by rob93c** [rob93c/Stickerify#14]
The section [_How to run the bot locally_](https://github.com/rob93c/Stickerify#How-to-run-the-bot-locally) is missing an explanation on how to launch it using Docker, for instance the command to run it should also handle the arg variable needed for it to be successfully started.

See also: [Setting Dynamic Environment Values](https://www.baeldung.com/ops/dockerfile-env-variable#dynamic_values)

**Comment by rishi-kai21** [comment]
Please Assign This Issue To Me

**Comment by rob93c** [comment]
Basically the documentation (readme) should explain how to launch the project using Docker. 
To be able to do so, you would need to pass the environment variable to the Docker command as explained in the guide [I linked](https://www.baeldung.com/ops/dockerfile-env-variable#dynamic_values).

I would add a new paragraph inside [How to run the bot locally](https://github.com/rob93c/Stickerify#How-to-run-the-bot-locally) explaining that, to run it with Docker, we need to use the command `docker build etc etc --build-arg etc etc`

I encourage you to try it on your PC to be sure you are writing a working command 📜

**Comment by rishi-kai21** [comment]
okay, thank you for explaining. I will update you when I commit any change to solve the problem.

**Comment by rishi-kai21** [comment]
> okay, thank you for explaining. I will update you when I commit any change to solve the problem.

 Whenever you get some time off please review my initial commitment and let me know of further improvements that can be made.
