### ISSUE TITLE
Unit test ImageHelper

### ISSUE THREAD

**Issue by rob93c** [rob93c/Stickerify#2]
Unit tests should be added for the class [`ImageHelper`](https://github.com/rob93c/StickerifyImageBot/blob/main/src/main/java/com/cellar/stickerifyimagebot/image/ImageHelper.java), they should be done using [JUnit Jupiter](https://github.com/junit-team/junit5).
Since the project currently hasn't the JUnit dependency, it must be added as part of this ticket (additional test dependencies might be added, _if needed_).

**There is no coverage goal**

- [ ] Add JUnit 5 dependency
- [ ] Add the test class `ImageHelperTest`
- [ ] Test given test cases

Test cases:
- [ ] Given big squared image, the result should be a 512x512 image
- [ ] Given a rectangular image with _side1_ > _side2_, the result should still have a _side1_ > _side2_ relationship
- [ ] Given a small image, the result should have its longer side of 512 pixels
- [ ] Given an invalid file, an error should be thrown
- [ ] Given an unsupported image (webp, gif or gifv), an error should be thrown

**Comment by kapilgahlot1998** [comment]
Hi,
Can I work on this issue. I have some knowledge on JUnit Testing.

**Comment by rob93c** [comment]
Hi @kapilgahlot1998! 
I'm happy to help if you want

Have fun 💯

**Comment by rob93c** [comment]
Hi @kapilgahlot1998, I updated the issue description with the test cases we should add.
Don't feel forced to work on the ticket if you changed your mind, just let me know in case 😃

**Comment by dalalvarun** [comment]
Hii,
i am curious to work on this. 
Should i start working on the tests?

**Comment by rob93c** [comment]
> Hii, i am curious to work on this. Should i start working on the tests?

Hi @dalalvarun and thanks for asking!
@kapilgahlot1998 asked to work on this first so I think we should let him play around with this ticket (unless he decides to let someone else work on it)

**Comment by dalalvarun** [comment]
Okay @rob93c 
@kapilgahlot1998 Let me know if you change your mind

**Comment by kapilgahlot1998** [comment]
Hi
I have completed my changes. But while pushing my changes I am getting permission denied. Can you help me here

**Comment by rob93c** [comment]
Hi @kapilgahlot1998! 
To be able to open a pull request you first need to fork the project (there's a button at the top of the page).
That will create a copy of the project under your account. You will need to apply your changes there and commit them.

If you manage to push the changes on your forked project, you will find an "open pull request" button on your project 😄 

This is Github's official guide on how to open a pull request: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

Let me know if you need further help

**Comment by rob93c** [comment]
Hi @kapilgahlot1998, do you need any help with this issue?
If you aim to complete the pull request in time for Hacktoberfest you have a few days left

**Comment by MartelliEnrico** [comment]
I can work on it!

**Comment by rob93c** [comment]
It's all yours, @MartelliEnrico 🧪
