### ISSUE TITLE
Add support for .webp files

### ISSUE THREAD

**Issue by rob93c** [rob93c/Stickerify#9]
The bot should be able to successfully process a .webp file and return the resized .png

**Comment by B-Stanley** [comment]
Hello, great project. I would like to be assigned this issue  please

**Comment by rob93c** [comment]
Hi @B-Stanley, do you need any help with this issue?
If you aim to complete the pull request in time for Hacktoberfest you have a few days left

**Comment by rob93c** [comment]
Hi @B-Stanley, as explained [here](https://github.com/rob93c/Stickerify/discussions/39), the ticket will be reassigned due to inactivity.
